from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import Keyword

NAMES = [
    "ACASTUS",
    "ADEPTUS ARBITES",
    "ADEPTUS MECHANICUS",
    "AGENTS OF THE IMPERIUM",
    "AIRCRAFT",
    "ARMIGER",
    "BATTLELINE",
    "CERASTUS",
    "CHARACTER",
    "CULT MECHANICUS",
    "DAEMON",
    "DEATHWATCH",
    "DEDICATED TRANSPORT",
    "DOMINUS",
    "ELECTRO-PRIESTS",
    "EPIC HERO",
    "FLY",
    "FRAME",
    "GRAVIS",
    "GRENADES",
    "HASTARII",
    "IMPERIAL KNIGHTS",
    "IMPERIUM",
    "INFANTRY",
    "INQUISITOR",
    "JUMP PACK",
    "KATAPHRON",
    "KILL TEAM",
    "KNIGHT ACHERON",
    "KNIGHT ASTERIUS",
    "KNIGHT ATRAPOS",
    "KNIGHT CASTIGATOR",
    "KNIGHT LANCER",
    "KNIGHT MAGAERA",
    "KNIGHT PORPHYRION",
    "KNIGHT STYRIX",
    "LEGIO CYBERNETICA",
    "MANIPULUS",
    "MARSHAL",
    "MOBILE",
    "MOIRAX",
    "MONSTER",
    "MOUNTED",
    "OFFICIO ASSASSINORUM",
    "ORDO HERETICUS",
    "ORDO MALLEUS",
    "ORDO XENOS",
    "PSYKER",
    "PTERAXII",
    "QUESTORIS",
    "RANGERS",
    "REQUISITIONED",
    "RETINUE",
    "SICARIAN",
    "SKITARII",
    "SMOKE",
    "SYDONIAN",
    "TACTICUS",
    "TECH-PRIEST",
    "TERMINATOR",
    "TERMINATOR SQUAD",
    "TITANIC",
    "TOWERING",
    "TRANSPORT",
    "VANGUARD",
    "VEHICLE",
    "VOIDFARERS",
    "WALKER",
]


async def seed(session: AsyncSession) -> None:
    existing = set((await session.execute(select(Keyword.name))).scalars().all())
    missing = [Keyword(name=name) for name in NAMES if name not in existing]
    if missing:
        session.add_all(missing)
        await session.commit()
